### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by dezudas** [ccoenraets/ionic2-realty#1]
It says 

./app/app.js
Module build failed: Error: Cannot resolve module 'ionic/ionic' in /Users/dd/mobileapp/IonicRealty/app
    Required in /Users/dijup/mobileapp/IonicRealty/app/app.js
    at ResolutionError.Error (native)
    at new ResolutionError (/Users/d/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/dist.babel/deps.js:482:88)
    at /Users/dijup/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/dist.babel/deps.js:301:37
    at tryCatcher (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/util.js:26:23)
    at CatchFilter.doFilter (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/catch_filter.js:52:40)
    at CatchFilter.tryCatcher (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/dd/mobileapp/IonicRealty/node_modules/awesome-typescript-loader/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:358:17)
 @ multi main (CLI v2.0.0-beta.17)

**Comment by dezudas** [comment]
My system info 
ordova CLI: 6.0.0
Gulp version:  CLI version 3.8.11
Gulp local:  
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: 1.8.4 
ios-sim version: 4.1.1 
OS: Mac OS X El Capitan
Node Version: v0.12.0
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by dezudas** [comment]
change ionic/ionic to ionic-framework/ionic
change in file path due to recent changes in framework structure
